nmHoistingLimits: workspaces

nodeLinker: node-modules

npmRegistries:
  'https://npm.pkg.github.com':
    npmAuthToken: '${NPM_TOKEN}'

npmScopes:
  noke-inc:
    npmRegistryServer: 'https://npm.pkg.github.com'
